<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    
    public function findMovieByPeriodAndSaga($saga, $periode)
    {
        $query = $this->createQueryBuilder('a')
        ->where(" a.idSaga = $saga and a.annee >= $periode")
        ->orderBy('a.annee', 'DESC')
        ->getQuery()
        ;
    
        return $query->getResult();
    }
    public function findMoviesPerAverage()
    {
        
        return $this->getEntityManager()
        ->createQuery(
            'SELECT AVG(v.note) as score_avg, f.id , f.titre, f.realisateur, f.annee FROM AppBundle:Film  f LEFT JOIN  AppBundle:Vote v WITH  v.idFilm = f.id group by f.id'
            )
            ->getResult();
        ;
    
    }
    public function findMovieByIdWithAverage($id){
        
        /*$query = $this->createQueryBuilder('f')
        ->select("avg(v.note) as score_avg, f.id , f.titre, f.realisateur, f.annee")        
        ->leftJoin('AppBundle:Vote', 'v',\Doctrine\ORM\Query\Expr\Join::WITH, 'f.id = v.idFilm')
        ->where('v.idFilm = :idFilm')
        ->setParameter('idFilm', $id)
        ->getQuery();*/
        
        return $this->getEntityManager()
        ->createQuery(
            "SELECT AVG(v.note) as score_avg, f.id , f.titre, f.realisateur, f.annee FROM AppBundle:Film  f LEFT JOIN  AppBundle:Vote v WITH  v.idFilm = f.id 
            where v.idFilm = $id"
            )
            ->getSingleResult();
    }
}
